services:
  app:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    environment:
      SLACK_TOKEN: $SLACK_TOKEN
      SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
