services:
  app:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    environment:
      SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
      SLACK_CLIENT_ID: $SLACK_CLIENT_ID
      SLACK_CLIENT_SECRET: $SLACK_CLIENT_SECRET
      APP_STATE_SECRET: $APP_STATE_SECRET
